global using AutoMapper;
global using ClinicHub.Core.Enums;
global using ClinicHub.Core.Models;
global using ClinicHub.Core.ViewModels;
global using ClinicHub.Interfaces;
global using ClinicHub.Services;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;